# Site
#repository: sproogen/resume-theme
repository: truth998877/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tony Ruther
title: Gas Turbine Performance Engineer
email: tony.ruther@googlemail.com
website: www.tonyruther.com

# Social links
#twitter_username: facespics
github_username:  truth998877
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  With 17+ years experience in the field of Gas Turbine Performance, 10 years working on Defence projects and 7 years working on Civil, I am actively looking for new opportunities within the Gas Turbine Performance field to further my career and broaden my experience.

  I spent 3 years living in Hanoi, Vietnam, during which time I took roles withinin the IT industry, online education and I teaching English as a foreign language.

  I spent 15 months travelling (July 2008 to Oct 2009), primarily overland, from the UK to Bali, via Japan, and beyond to Australia and New Zealand.

  I am married with one child at present.

 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: More About Me
more_content: | # this will include new lines to allow paragraphs

    - Astronomy - *I have recently started doing back garden astronomy. I own two telescopes a 127mm f/7.87 Newtonian reflector and an 80mm f/15 refractor*

    - Karate - *I have practiced karate since university*

    - Linux Terminal - *Bash, tmux, vi/m, lynx browser - recently made a real effort to carry out most of my work from the linux command line, including the creation of this site and the sites I detail in the 'Projects' section*

    - Coding - *I am activly increasing my coding skills both at work and outside, mainly MATLAB and Bash Scripting, although recently my role has required me to work in npss (Numerical Propulsion System Simulation, an advanced object-oriented, non-linear thermodynamic modeling environment used by the aerospace industry for modeling turbomachinery, air-breathing propulsion systems, liquid rocket engines, engine control systems, and system model integration)*

    - [Gaming](https://www.fortiesgamer.com) - *On Linux!*

# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme
remote_theme: truth998877/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
